# Generated by Django 4.2.2 on 2023-06-13 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_remove_client_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='project',
            field=models.ManyToManyField(null=True, to='myapp.project'),
        ),
    ]
