# Generated by Django 4.2.2 on 2023-06-13 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_client_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='project',
        ),
    ]
